#pragma once

#ifndef LabSoundIncludes_h
#define LabSoundIncludes_h

// Configuration
#include "src/LabSound/LabSoundConfig.h"

// LabSound Extensions
#include "src/LabSound/LabSound.h"
#include "src/LabSound/ADSRNode.h"
#include "src/LabSound/DiodeNode.h"
#include "src/LabSound/RecorderNode.h"
#include "src/LabSound/SoundBuffer.h"
#include "src/LabSound/SpatializationNode.h"
#include "src/LabSound/SfxrNode.h"
#include "src/LabSound/SupersawNode.h"
#include "src/LabSound/NoiseNode.h"
#include "src/LabSound/ClipNode.h"
#include "src/LabSound/PdNode.h"

// Important WTFs
#include "src/WTF/wtf/ExportMacros.h"
#include "src/WTF/wtf/OwnArrayPtr.h"
#include "src/WTF/wtf/PassRefPtr.h"
#include "src/WTF/wtf/RefPtr.h"
#include "src/WTF/wtf/Threading.h"
#include "src/WTF/wtf/Float32Array.h"
#include "src/WTF/wtf/ArrayBuffer.h"

// Webaudio Public APIS
#include "src/Modules/webaudio/AnalyserNode.h"              
#include "src/Modules/webaudio/ChannelMergerNode.h"
#include "src/Modules/webaudio/AsyncAudioDecoder.h" 
#include "src/Modules/webaudio/ChannelSplitterNode.h"
#include "src/Modules/webaudio/AudioBasicInspectorNode.h" 
#include "src/Modules/webaudio/ConvolverNode.h"
#include "src/Modules/webaudio/AudioBasicProcessorNode.h" 
#include "src/Modules/webaudio/DefaultAudioDestinationNode.h"
#include "src/Modules/webaudio/AudioBuffer.h" 
#include "src/Modules/webaudio/DelayDSPKernel.h"
#include "src/Modules/webaudio/AudioBufferCallback.h" 
#include "src/Modules/webaudio/DelayNode.h"
#include "src/Modules/webaudio/AudioBufferSourceNode.h" 
#include "src/Modules/webaudio/DelayProcessor.h"
#include "src/Modules/webaudio/AudioContext.h"
#include "src/Modules/webaudio/DynamicsCompressorNode.h"
#include "src/Modules/webaudio/AudioDestinationNode.h" 
#include "src/Modules/webaudio/GainNode.h"
#include "src/Modules/webaudio/AudioGain.h"
#include "src/Modules/webaudio/MediaElementAudioSourceNode.h"
#include "src/Modules/webaudio/AudioListener.h" 
#include "src/Modules/webaudio/MediaStreamAudioDestinationNode.h"
#include "src/Modules/webaudio/AudioNode.h"
#include "src/Modules/webaudio/MediaStreamAudioSourceNode.h"
#include "src/Modules/webaudio/AudioNodeInput.h" 
// #include "src/Modules/webaudio/OfflineAudioCompletionEvent.h" // gpl conflict with included file Event.h
#include "src/Modules/webaudio/AudioNodeOutput.h" 
#include "src/Modules/webaudio/OfflineAudioDestinationNode.h"
#include "src/Modules/webaudio/AudioParam.h" 
#include "src/Modules/webaudio/OscillatorNode.h"
#include "src/Modules/webaudio/AudioParamTimeline.h" 
#include "src/Modules/webaudio/PannerNode.h"
// #include "src/Modules/webaudio/AudioProcessingEvent.h" // gpl conflict with included file Event.h 
#include "src/Modules/webaudio/RealtimeAnalyser.h"
#include "src/Modules/webaudio/AudioScheduledSourceNode.h" 
#include "src/Modules/webaudio/ScriptProcessorNode.h"
#include "src/Modules/webaudio/AudioSourceNode.h" 
#include "src/Modules/webaudio/WaveShaperDSPKernel.h"
#include "src/Modules/webaudio/AudioSummingJunction.h" 
#include "src/Modules/webaudio/WaveShaperNode.h"
#include "src/Modules/webaudio/BiquadDSPKernel.h" 
#include "src/Modules/webaudio/WaveShaperProcessor.h"
#include "src/Modules/webaudio/BiquadFilterNode.h" 
#include "src/Modules/webaudio/WaveTable.h"
#include "src/Modules/webaudio/BiquadProcessor.h"

// Shims
#include "src/shim/ActiveDOMObject.h"
#include "src/shim/ContextDestructionObserver.h"
#include "src/shim/EventListener.h"
#include "src/shim/EventTarget.h"
#include "src/shim/ExceptionCode.h"
#include "src/shim/LengthFunctions.h"
#include "src/shim/MediaStream.h"
// #include "src/shim/WebCoreMemoryInstrumentation.h

// Not-so-internal things
#include "src/platform/audio/AudioArray.h"
#include "src/platform/audio/AudioBus.h"
#include "src/platform/audio/AudioChannel.h"
#include "src/platform/audio/AudioDSPKernel.h"
#include "src/platform/audio/AudioDSPKernelProcessor.h"
#include "src/platform/audio/AudioDestination.h"
#include "src/platform/audio/AudioDestinationConsumer.h"
#include "src/platform/audio/AudioFIFO.h"
#include "src/platform/audio/AudioFileReader.h"
#include "src/platform/audio/AudioIOCallback.h"
#include "src/platform/audio/AudioProcessor.h"
#include "src/platform/audio/AudioPullFIFO.h"
#include "src/platform/audio/AudioResampler.h"
#include "src/platform/audio/AudioResamplerKernel.h"
#include "src/platform/audio/AudioSourceProvider.h"
#include "src/platform/audio/AudioSourceProviderClient.h"
#include "src/platform/audio/AudioUtilities.h"
#include "src/platform/audio/Biquad.h"
#include "src/platform/audio/Cone.h"
#include "src/platform/audio/DenormalDisabler.h"
#include "src/platform/audio/DirectConvolver.h"
#include "src/platform/audio/Distance.h"
#include "src/platform/audio/DynamicsCompressor.h"
#include "src/platform/audio/DynamicsCompressorKernel.h"
#include "src/platform/audio/EqualPowerPanner.h"
#include "src/platform/audio/FFTConvolver.h"
#include "src/platform/audio/FFTFrame.h"
#include "src/platform/audio/HRTFDatabase.h"
#include "src/platform/audio/HRTFDatabaseLoader.h"
#include "src/platform/audio/HRTFElevation.h"
#include "src/platform/audio/HRTFKernel.h"
#include "src/platform/audio/HRTFPanner.h"
#include "src/platform/audio/MultiChannelResampler.h"
#include "src/platform/audio/Panner.h"
#include "src/platform/audio/Reverb.h"
#include "src/platform/audio/ReverbAccumulationBuffer.h"
#include "src/platform/audio/ReverbConvolver.h"
#include "src/platform/audio/ReverbConvolverStage.h"
#include "src/platform/audio/ReverbInputBuffer.h"
#include "src/platform/audio/SincResampler.h"
#include "src/platform/audio/VectorMath.h"
#include "src/platform/audio/ZeroPole.h"

#include "src/platform/graphics/FloatPoint.h"
#include "src/platform/graphics/FloatQuad.h"
#include "src/platform/graphics/FloatRect.h"
#include "src/platform/graphics/FloatSize.h"
#include "src/platform/graphics/IntPoint.h"
#include "src/platform/graphics/IntRect.h"
#include "src/platform/graphics/IntSize.h"
// #include "src/platform/graphics/LayoutPoint.h"
// #include "src/platform/graphics/LayoutRect.h"
// #include "src/platform/graphics/LayoutSize.h"

#endif