version: 1.0.{build}

image: Visual Studio 2017

platform: x64
configuration: 
  - Release
  - Debug

install:
  - git submodule update --init --recursive

build:
  verbosity: minimal
  project: examples/win.vs2017/LabSoundExamples.sln